# Общие настройки для всех окружений
[default]
environment = "development"      # Окружение приложения (development, testing, production)
debug = true                     # Режим отладки
api_v1_str = "/api/v1"           # Префикс для API v1
project_name = "API Server"      # Название проекта
version = "0.1.0"                # Версия приложения

# Настройки для внешних API
station_workload_url = ""        # URL API для получения загруженности остановок (если пустое, будет использоваться случайное значение)
two_gis_base_url = "https://catalog.api.2gis.com/3.0/items"  # Базовый URL для 2GIS API

# Параметры для построения маршрутов
transport_search_radius = 500    # Радиус поиска транспорта (метры)
max_stop_count = 5               # Максимальное количество остановок для поиска

# Настройки журналирования
log_level = "DEBUG"               # Уровень логирования (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log_rotation = "1 day"           # Период ротации файлов журнала
log_retention = "7 days"         # Период хранения файлов журнала
log_format = "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"

[development]
debug = true

[production]
debug = false
station_workload_url = "http://localhost:8080"
log_level = "WARNING"  # В продакшене повышаем уровень логирования