version: '3.8'

services:
  apiserver:
    build:
      context: ../backend/apiserver
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - apiserver_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/status/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app_network

volumes:
  apiserver_logs:

networks:
  app_network:
    driver: bridge
